
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT = 'LOGOUT';
export const ADD_ERRORS = 'ADD_ERRORS';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';
export const START_CALL  = 'START_CALL';
export const END_CALL = 'END_CALL';
export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';
export const REMOVE_USER_DETAILS = 'REMOVE_USER_DETAILS';
export const ADD_SUCCESS_MESSAGES = 'ADD_SUCCESS_MESSAGES';
export const REMOVE_SUCCESS_MESSAGES = 'REMOVE_SUCCESS_MESSAGES';